parse obj_info lines as comments
FugroRoames/PlyIO.jl pull request #13
Opened 2020-02-05 16:35 UTC by heliosdrm

Some libraries add lines starting with `obj_info` to the header. This is a quick fix to be able to read such files, storing the `obj_info` lines as if they were just additional comments.

2020-02-20 01:45 UTC, c42f requested changes
Thanks for this!

I think we need a test for this functionality.

Namely, does this allow you to exactly "round-trip" the ply file? Reading will work ok, but it looks to me that `obj_info` will be wrapped with a redundant `comment` prefix when writing back to the ply file.

2020-02-20 10:07 UTC, heliosdrm commented
I'm not sure about the best way to extend this. Shall we introduce a new type e.g. `PlyObjInfo`, and extend `Ply` to contain a vector of such elements? Or - less breaking - store `obj_info` lines as `PlyComment`s, and modify the function for writing files, such that comments starting with `obj_info` are written without the `"comment"` tag?

The second approach looks dirtier, but there is a point in storing `obj_info` lines as comments, since `obj_info` is not actually defined in the original PLY specification (cf. http://gamma.cs.unc.edu/POWERPLANT/papers/ply.pdf). Definitions elsewhere are inconsistent: [here](http://w3.impa.br/~diego/software/rply/) it is defined as a line containing "meta-information about the object" (implicitly in free text); whereas [this specification](http://docs.pointclouds.org/1.5.1/structpcl_1_1io_1_1ply_1_1obj__info.html) seems to imply that it can contain numeric information.

2020-02-21 05:18 UTC, c42f commented
> store `obj_info` lines as `PlyComment`s, and modify the function for writing files, such that comments starting with `obj_info` are written without the `"comment"` tag?

I think this kind of thing is fine. To be a bit more precise and less "stringly typed", let's add a new `Bool` field to `PlyComment` called `is_obj_info`, and populate that as required (should be able to give it default values to make the API backward compatible).

That way round-trip is more precise if someone is unfortunate enough to write a header line starting with

```
comment obj_info <blah blah>
```

2020-02-21 05:22 UTC, c42f commented
> `obj_info` is not actually defined in the original PLY specification [...] Definitions elsewhere are inconsistent

Oh by the way I think your reasoning is spot-on here about why we should use a string for representation.

The PCL reference seems to suggest that `obj_info` is for supplying key-value pairs where the values are numeric. We can always provide a utility function later for adding and extracting such metadata from the comment list.

2020-03-12 04:31 UTC, c42f approved these changes
I thought I'd push this along by doing the suggested refactor and updating this PR. CI seems to have passed, so I think we're good to go here.

Do you think the changes I've done here will work for you?

2020-03-16 07:52 UTC, merged